{% set version = "0.10.1" %}


package:
  name: pyagrum
  version: {{ version }}

source:
  git_url: git://forge.lip6.fr/aGrUM
  git_tag: {{ version }}
  patches:
    - 0001-Allow-to-define-PYTHON_INSTALL.patch

build:
  number: 1
  features:
    - vc14  # [win and py35]
  skip: true  # [win and py < 35]

requirements:
  build:
    # use gcc instead of clang on osx because of the cxx14 requirement
    - toolchain  # [linux]
    - gcc  # [osx]
    - python
    - numpy
    - cmake
  run:
    - python
    - numpy
    - libgcc  # [osx]
    - pydotplus
    - matplotlib

test:
  requires:
    - ipython
  imports:
    - pyAgrum
    - pyAgrum.lib.bn2csv
    - pyAgrum.lib.bn2roc
    - pyAgrum.lib.dynamicBN
    - pyAgrum.lib.notebook

about:
  home: https://forge.lip6.fr/projects/aGrUM/wiki
  license: GPLv3
  license_file: COPYRIGHT.txt
  summary: C++ Bayesian networks library

extra:
  recipe-maintainers:
    - jschueller
