{% set version = "2.3.0" %} 

package:
  name: pyagrum
  version: {{ version }}

source:
  fn: pyagrum-{{ version }}.tar.bz2
  url: https://gitlab.com/agrumery/aGrUM/-/archive/{{ version }}/aGrUM-{{ version }}.tar.bz2
  sha256: 9b55a129c37c7c375204d9e851cedfe977319bdf3e9cc971c0f67219b9721ae2

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('pyagrum', max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - swig
    - {{ compiler('c') }}  # [unix]
    - {{ stdlib("c") }}    # [unix]
    - {{ compiler('cxx') }}  # [unix] 
  host:
    - python
    - numpy
    - pydot
    - six
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas
    - matplotlib-inline
    - scikit-learn
    - scipy
  run:
    - python
    - numpy
    - pydot
    - six
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas
    - matplotlib-inline
    - scikit-learn
    - scipy

test:
  requires:
    - ipykernel
  imports:
    - pyagrum
    - pyagrum.lib.bn2roc
    - pyagrum.lib.bn2scores
    - pyagrum.lib.bn_vs_bn
    - pyagrum.lib.dynamicBN
    - pyagrum.lib.notebook

about:
  home: http://agrum.gitlab.io/
  license: LGPL-3.0-only OR MIT
  license_file:
    - LICENSE.md
    - LICENSE.LGPL
    - LICENSE.MIT
  license_url: https://gitlab.com/agrumery/aGrUM/-/blob/master/LICENSE.md
  summary: pyAgrum is a scientific C++ and Python library dedicated to Bayesian Networks and other Probabilistic Graphical Models.
  description: |
    aGrUM is a C++ library for graphical models. It is designed for easily building applications
    using graphical models such as Bayesian networks, influence diagrams, decision trees, GAI networks
    or Markov decision processes. pyAgrum provides a high-level interface to the part of aGrUM allowing
    to create, model, learn, use, calculate with and embed Bayesian Networks and other graphical models.
    Some specific (python and C++) codes are added in order to simplify and extend the aGrUM API.

    Since pyAgrum 2.0.0, the package name follows PEP8 rules and is now pyagrum (lowercase). 
    
    Please use:
      
      import pyagrum

    Instead of:

      import pyAgrum

    See the CHANGELOG (https://gitlab.com/agrumery/aGrUM/-/blob/master/CHANGELOG.md?ref_type=heads#changelog-for-200) for more details.
  doc_url: https://pyagrum.readthedocs.io/
  dev_url: https://gitlab.com/agrumery/aGrUM

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
    - aspard
