{% set version = "0.13.4" %}

package:
  name: pyagrum
  version: {{ version }}

source:
  fn: pyagrum-{{ version }}.tar.bz2
  url: https://gitlab.com/agrumery/aGrUM/repository/archive.tar.bz2?ref={{ version }}
  sha256: c1a027cc24a39148c990e400ea64cb7ae4b65fad78094991dbd9109362d29cfa

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    #- {{ compiler('m2w64_c') }}  # [win]
    #- {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - python
    #- libpython  # [win]
    - numpy
  run:
    - python
    - numpy
    - pydotplus
    - matplotlib

test:
  requires:
    - ipython
  imports:
    - pyAgrum
    - pyAgrum.lib.bn2roc
    - pyAgrum.lib.bn2scores
    - pyAgrum.lib.bn_vs_bn
    - pyAgrum.lib.dynamicBN
    - pyAgrum.lib.notebook
    - pyAgrum.lib.pretty_print

about:
  home: http://agrum.gitlab.io/
  license: GPL3
  license_file: COPYRIGHT.txt
  summary: A wrapper for the Agrum library, to make flexible and scalable probabilistic graphical models.

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
