{% set version = "2.3.1" %} 

package:
  name: pyagrum
  version: {{ version }}

source:
  fn: pyagrum-{{ version }}.tar.bz2
  url: https://gitlab.com/agrumery/aGrUM/-/archive/{{ version }}/aGrUM-{{ version }}.tar.bz2
  sha256: b8c51b4d32539cf7b9e523c30e832f4e535148174c86e623fbd6392c4ba4405d

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('pyagrum', max_pin='x.x.x') }}
  python_version_independent: true  # [is_abi3]
  skip: True  # [is_abi3 and not is_python_min]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - swig
    - {{ compiler('c') }}  # [unix]
    - {{ stdlib("c") }}    # [unix]
    - {{ compiler('cxx') }}  # [unix] 
  host:
    - python-abi3  # [is_abi3]
    - python
    - numpy
    - pydot
    - six
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas
    - matplotlib-inline
    - scikit-learn
    - scipy
  run:
    - python
    - numpy
    - pydot
    - six
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas
    - matplotlib-inline
    - scikit-learn >=1.7
    - scipy

test:
  requires:
    - ipykernel
    - abi3audit  # [is_abi3]
  imports:
    - pyagrum
    - pyagrum.lib.bn2roc
    - pyagrum.lib.bn2scores
    - pyagrum.lib.bn_vs_bn
    - pyagrum.lib.dynamicBN
    - pyagrum.lib.notebook
  commands:
    - abi3audit $SP_DIR/pyagrum/_pyagrum.so -s -v --assume-minimum-abi3 3.10  # [unix and is_abi3]

about:
  home: http://agrum.gitlab.io/
  license: LGPL-3.0-only OR MIT
  license_file:
    - LICENSE.md
    - LICENSE.LGPL
    - LICENSE.MIT
  license_url: https://gitlab.com/agrumery/aGrUM/-/blob/master/LICENSE.md
  summary: pyAgrum is a scientific C++ and Python library dedicated to Bayesian Networks and other Probabilistic Graphical Models.
  description: |
    aGrUM is a C++ library for graphical models. It is designed for easily building applications
    using graphical models such as Bayesian networks, influence diagrams, decision trees, GAI networks
    or Markov decision processes. pyAgrum provides a high-level interface to the part of aGrUM allowing
    to create, model, learn, use, calculate with and embed Bayesian Networks and other graphical models.
    Some specific (python and C++) codes are added in order to simplify and extend the aGrUM API.

    Since pyAgrum 2.0.0, the package name follows PEP8 rules and is now pyagrum (lowercase). 
    
    Please use:
      
      import pyagrum

    Instead of:

      import pyAgrum

    See the CHANGELOG (https://gitlab.com/agrumery/aGrUM/-/blob/master/CHANGELOG.md?ref_type=heads#changelog-for-200) for more details.
  doc_url: https://pyagrum.readthedocs.io/
  dev_url: https://gitlab.com/agrumery/aGrUM

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
    - aspard
