{% set version = "1.6.1" %} 

package:
  name: pyagrum
  version: {{ version }}

source:
  fn: pyagrum-{{ version }}.tar.bz2
  url: https://gitlab.com/agrumery/aGrUM/-/archive/{{ version }}/aGrUM-{{ version }}.tar.bz2
  sha256: 9fa1eb3e8789f290ce7af17ae206507696a4316678f68a6e4ce1e3fa311ad31e

build:
  number: 0
  skip: true  # [py<38]
  run_exports:
    - {{ pin_subpackage('pyagrum', max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix] 
    - curl  # [win]
    - 7za  # [win]
  host:
    - python
    - numpy
    - pydot
    - six
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas
    - matplotlib-inline
    - scikit-learn
    - scipy
  run:
    - python
    - numpy
    - pydot
    - six
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas
    - matplotlib-inline
    - scikit-learn
    - scipy

test:
  requires:
    - ipykernel
  imports:
    - pyAgrum
    - pyAgrum.lib.bn2roc
    - pyAgrum.lib.bn2scores
    - pyAgrum.lib.bn_vs_bn
    - pyAgrum.lib.dynamicBN
    - pyAgrum.lib.notebook

about:
  home: http://agrum.gitlab.io/
  license: LGPL-3.0-only
  license_file: COPYRIGHT.txt
  summary: pyAgrum is a Python wrapper for the C++ aGrUM library. It provides a high-level interface to the part of aGrUM allowing to create, model, learn, use, calculate with and embed Bayesian networks and other graphical models. Some specific (Python and C++) codes are added in order to simplify and extend the aGrUM API.

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
    - aspard
