{% set version = "0.17.3" %} 

package:
  name: pyagrum
  version: {{ version }}

source:
  fn: pyagrum-{{ version }}.tar.bz2
  url: https://gitlab.com/agrumery/aGrUM/-/archive/{{ version }}/aGrUM-{{ version }}.tar.bz2
  sha256: 5676f244da53a958eb812bc967781c13d1c1deab14a0edbd01d0e9fb75a5cfdd

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pyagrum', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - curl  # [win]
  host:
    - python
    - numpy
    - pydotplus
    - six
    - configparser  # [py2k]
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas
  run:
    - python
    - numpy
    - pydotplus
    - six
    - configparser  # [py2k]
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas

test:
  requires:
    - ipykernel
  imports:
    - pyAgrum
    - pyAgrum.lib.bn2roc
    - pyAgrum.lib.bn2scores
    - pyAgrum.lib.bn_vs_bn
    - pyAgrum.lib.dynamicBN
    - pyAgrum.lib.notebook
    - pyAgrum.lib.pretty_print

about:
  home: http://agrum.gitlab.io/
  license: LGPL-3.0-only
  license_file: COPYRIGHT.txt
  summary: pyAgrum is a Python wrapper for the C++ aGrUM library. It provides a high-level interface to the part of aGrUM allowing to create, model, learn, use, calculate with and embed Bayesian Networks and other graphical models. Some specific (python and C++) codes are added in order to simplify and extend the aGrUM API.

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
    - aspard
