{% set version = "0.11.2" %}

package:
  name: pyagrum
  version: {{ version }}

source:
  fn: pyagrum-{{ version }}.tar.bz2
  url: https://gitlab.com/agrumery/aGrUM/repository/archive.tar.bz2?ref={{ version }}
  sha256: 65ce55ede74aa21737e4cefef76ed88d2f37c6b7b4332468289f1f94e80eebc5

build:
  number: 0
  features:
    - vc14  # [win and py>=35]
  skip: true  # [win and py<35]

requirements:
  build:
    # use gcc instead of clang on osx because of the cxx14 requirement
    - toolchain  # [linux]
    - gcc  # [osx]
    - python
    - numpy
    - cmake
  run:
    - python
    - numpy
    - libgcc  # [osx]
    - pydotplus
    - matplotlib

test:
  requires:
    - ipython
  imports:
    - pyAgrum
    - pyAgrum.lib.bn2csv
    - pyAgrum.lib.bn2roc
    - pyAgrum.lib.bn2scores
    - pyAgrum.lib.bn_vs_bn
    - pyAgrum.lib.dynamicBN
    - pyAgrum.lib.notebook
    - pyAgrum.lib.pretty_print

about:
  home: http://agrum.gitlab.io/
  license: GPL3
  license_file: COPYRIGHT.txt
  summary: C++ Bayesian networks library

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
