{% set version = "0.16.4" %}

package:
  name: pyagrum
  version: {{ version }}

source:
  fn: pyagrum-{{ version }}.tar.bz2
  url: https://gitlab.com/agrumery/aGrUM/-/archive/{{ version }}/aGrUM-{{ version }}.tar.bz2
  sha256: 0c44d3a1ea9d1c7b947a8ff74e62b3d905b62a407edb0c92e929e2df4955f5d1

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pyagrum', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
  host:
    - python
    - numpy
    - pydotplus
    - six
    - configparser  # [py2k]
    - matplotlib
    - IPython
    - ipykernel
  run:
    - python
    - numpy
    - pydotplus
    - six
    - configparser  # [py2k]
    - matplotlib
    - IPython
    - ipykernel

test:
  requires:
    - ipykernel
  imports:
    - pyAgrum
    - pyAgrum.lib.bn2roc
    - pyAgrum.lib.bn2scores
    - pyAgrum.lib.bn_vs_bn
    - pyAgrum.lib.dynamicBN
    - pyAgrum.lib.notebook
    - pyAgrum.lib.pretty_print

about:
  home: http://agrum.gitlab.io/
  license: LGPL3
  license_file: COPYRIGHT.txt
  summary: A wrapper for the Agrum library, to make flexible and scalable probabilistic graphical models.

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
    - aspard
