context:
  version: "2.3.2"

package:
  name: pyagrum
  version: ${{ version }}

source:
  url: https://gitlab.com/agrumery/aGrUM/-/archive/${{ version }}/aGrUM-${{ version }}.tar.bz2
  sha256: c7cb9988a015b9abe29fb008e73d89f54dd0e3826550e7a3910fdcdd245c0484

build:
  number: 1
  python:
    version_independent: true

requirements:
  build:
    - cmake
    - swig
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: unix
      then: make
      else: ninja
    - if: build_platform != target_platform
      then:
        - python ${{ python_min }}.*
        - python-abi3 ${{ python_min }}.*
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - python ${{ python_min }}.*
    - python-abi3 ${{ python_min }}.*
    - numpy
    - pydot
    - six
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas
    - matplotlib-inline
    - scikit-learn
    - scipy
  run:
    - python >=${{ python_min }}
    - numpy
    - pydot
    - six
    - matplotlib-base
    - IPython
    - ipykernel
    - pandas
    - matplotlib-inline
    - scikit-learn >=1.7
    - scipy
  run_exports:
    - ${{ pin_subpackage('pyagrum', upper_bound='x.x.x') }}

tests:
  - python:
      imports:
        - pyagrum
        - pyagrum.lib.bn2roc
        - pyagrum.lib.bn2scores
        - pyagrum.lib.bn_vs_bn
        - pyagrum.lib.dynamicBN
        - pyagrum.lib.notebook
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  homepage: https://pyagrum.gitlab.io/
  license: LGPL-3.0-only OR MIT
  license_file:
    - LICENSE.md
    - LICENSE.LGPL
    - LICENSE.MIT
  summary: pyAgrum is a scientific C++ and Python library dedicated to Bayesian Networks and other Probabilistic Graphical Models.
  description: |
    aGrUM is a C++ library for graphical models. It is designed for easily building applications
    using graphical models such as Bayesian networks, influence diagrams, decision trees, GAI networks
    or Markov decision processes. pyAgrum provides a high-level interface to the part of aGrUM allowing
    to create, model, learn, use, calculate with and embed Bayesian Networks and other graphical models.
    Some specific (python and C++) codes are added in order to simplify and extend the aGrUM API.

    Since pyAgrum 2.0.0, the package name follows PEP8 rules and is now pyagrum (lowercase). 
    
    Please use:
      
      import pyagrum

    Instead of:

      import pyAgrum

    See the CHANGELOG (https://gitlab.com/agrumery/aGrUM/-/blob/master/CHANGELOG.md?ref_type=heads#changelog-for-200) for more details.
  documentation: https://pyagrum.readthedocs.io/
  repository: https://gitlab.com/agrumery/aGrUM

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
    - aspard
