appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: utBlndzO1v6UATf80z2nOvVghXOK6CBZekb7X6tri7PuqhaVt901p40K0nAwiD9hvFWYQJ8dBSSc7Y+cYEd8tAw2Ip2VmAR/brLWeHvwmmHRAmbSuMb0A9NHZsCyKCe2nBakoiIrLTgd+tcekd6ZkjkLD60UDG0ZpPPW4X8dYbcmTA36mxfdOp+Wr0/OrBctGuS7Tfz8Qc4atSvpyYrZkTj5N4+X0MPvZCHpkb1d3Sk/9Z7qoePVmtflKbTsM/FGmLM8xovie28Z3CiHso8l8qQIuBDBdFT7jJKlhKiNFvf2hVrqtlzcmCSIFeVEVLYCtA/pi2/b5eq/5BZ0TOnOzCL809nMtmWgLtAhtTfKSs9koUSETIBWWts2c1mkXbqpOyrmU1uhwjybZe4Is2VSbpMRyUSbt0LoTbDxS8duVGVYsmefM//SxeaGTsHAnXOPvq0CR6Nxf3BnEgXmwxvAASz/BShddFQkEDkzpW/65Jt0HT4Ji1G5FK/wfkwfcsMeOjkpDBeYJkXJO4BxTjD1ZjFW4I9qs+58VrxSnv68sWLMmz4w8LI2cz0txOr+aOxTEjvhBcKM1PkY9AXjGPBz5fNsY1lI3Jkus6xKjxbNPlVOqruxtNDWR41hSOJYxIsDyFrdkh0FVKpoLWyUWszBRNRsVo9mGGKZbZAvJlA6jyU=}
